### ISSUE TITLE
好像私有部署服务器登录不上去

### ISSUE THREAD

**Issue by nnkn** [TankNee/Neeto-Vue#24]
点击登录没有任何反应，这和我有自定义端口8081有关系吗？

**Comment by TankNee** [comment]
应该是没有关系的，请问是只有私有部署的登不上去吗？官方服务可以正常运行吗？

**Comment by TankNee** [comment]
如果可以的话，能否给我一个测试账号，因为publish版本没有办法打开开发者工具，我需要在本地调试一下

**Comment by nnkn** [comment]
官方的正常登录的，就私有的上不去，我这个外网暂时访问不了...

**Comment by TankNee** [comment]
好。谢谢，我先找找问题，因为我没有测试过本地的docker

**Comment by nnkn** [comment]
嗯嗯，谢谢啦！

**Comment by TankNee** [comment]
我刚刚也测试了一下带端口的地址，是没有问题的。
是不是因为你的地址最后带了`/`导致解析失败呢？地址最后不要携带其他字符，应该只保留端口数字。

**Comment by nnkn** [comment]
登录进去了，地址最后我没有加/的，但是前面我也没有加http://，直接是写ip:port的形式，因为官方客户端不填这个也能登录进去。
感谢大佬启发，我写成了http://ip:port 就能进了……

**Comment by yournyk** [comment]
私有服务器有开源么？给个地址？
