### ISSUE TITLE
mac 无法展开目录，转移功能也不能用

### ISSUE THREAD

**Issue by xhbpiao** [TankNee/Neeto-Vue#48]
图1：
![image](https://user-images.githubusercontent.com/8832402/100865947-f568e180-34d2-11eb-9b06-f7fd53b9f9a7.png)
图2：
![image](https://user-images.githubusercontent.com/8832402/100865971-00237680-34d3-11eb-9bb7-f15b2f5404d6.png)
图3：
![image](https://user-images.githubusercontent.com/8832402/100865992-07e31b00-34d3-11eb-9560-0b0649c73a6c.png)

**Comment by xhbpiao** [comment]
点击切换视图 ，只能在 1 和2 图切换。 点击目结构 会出现图3的情况

**Comment by TankNee** [comment]
请问您在为知的网页端可以看到文件夹吗

**Comment by xhbpiao** [comment]
在网页端和 wizNote 上面 都可以看到
![image](https://user-images.githubusercontent.com/8832402/100866399-8f308e80-34d3-11eb-95bd-baf0344331d7.png)

**Comment by TankNee** [comment]
使用command+option+i可以调用Chrome开发者工具，你能看一下网络调用吗。或者你给我一个测试账号我来看一下？

**Comment by xhbpiao** [comment]
![image](https://user-images.githubusercontent.com/8832402/100867122-b0de4580-34d4-11eb-91cb-64fc164e23f4.png)
![image](https://user-images.githubusercontent.com/8832402/100867177-c6536f80-34d4-11eb-8b09-b2010c389dfa.png)
![image](https://user-images.githubusercontent.com/8832402/100867249-e2571100-34d4-11eb-8856-843dcaffa15c.png)

**Comment by TankNee** [comment]
ctrl+R刷新可以重新加载一遍。看看有没有这个URL的请求
![image](https://user-images.githubusercontent.com/43956168/100867467-382bb900-34d5-11eb-8bcb-e5f6020733f6.png)
他的返回体是这样的
![image](https://user-images.githubusercontent.com/43956168/100867555-542f5a80-34d5-11eb-8c08-6dddaaba9ae2.png)

**Comment by xhbpiao** [comment]
上面zui最后一个图就是
![image](https://user-images.githubusercontent.com/8832402/100867864-bee09600-34d5-11eb-91fa-1d64b6152b57.png)

**Comment by xhbpiao** [comment]
上面最后一个图就是 
![image](https://user-images.githubusercontent.com/8832402/100867994-ee8f9e00-34d5-11eb-9a00-60a958b0370f.png)

**Comment by TankNee** [comment]
感谢，我会尽快定位错误的。这个报错之前也出现过，我会尽快解决的

**Comment by xhbpiao** [comment]
🙏

**Comment by xhbpiao** [comment]
我追了一下你的代码 ，你的多级目录处理有问题

**Comment by TankNee** [comment]
> 我追了一下你的代码 ，你的多级目录处理有问题

愿闻其详，那一块没做太多测试

**Comment by xhbpiao** [comment]
![image](https://user-images.githubusercontent.com/8832402/100889284-eba2a680-34f1-11eb-8c0d-33c1ec61fa3c.png)
你这一块 只对 单级目录做了处理。 多级的 result 没有添加值 ，导致后面 的    const rootNodeIndex = result.findIndex(c => c.label === category[0])
这里匹配不到

**Comment by xhbpiao** [comment]
问题 就出在这一块了 ，你思考一下 ，也可以debug 一下。 我明天再继续看

**Comment by TankNee** [comment]
感谢。

**Comment by TankNee** [comment]
很奇怪的一件事，我的私有部署服务器返回的数据中，这个文件夹列表是有顺序的，是按照父文件夹，子文件夹这样一层层下来的。你的服务器好像不太一样？

**Comment by TankNee** [comment]
例如
![image](https://user-images.githubusercontent.com/43956168/100890861-a8e1ce00-34f3-11eb-92d8-fbe928b58af3.png)
`/My Notes/`下面跟的是`/My Notes/数据结构/`

**Comment by TankNee** [comment]
我的代码是基于这个逻辑写的，比较偷懒。我把这个地方改一下，适配你这种情况

**Comment by xhbpiao** [comment]
result 的 内容似乎有随机性， 一个简单的解决办法就是sort 一下

**Comment by TankNee** [comment]
新版本正在构建，可以等一会儿在releases页面查看。
我简单地排了一下文件夹列表。
