### ISSUE TITLE
1.0.2私有地址无法登陆

### ISSUE THREAD

**Issue by ArthurSmoke** [TankNee/Neeto-Vue#62]
### 环境
MacOS Big Sur 11.0.1
### 现象
私有部署点击登陆无反应，页没有报错
公有环境正常
私有地址填的`http://nas.xiaolong.fun:3007`
### 账号
提供一个测试账号
http://nas.xiaolong.fun:3007/
account:`test@test.com`
password:`testtest`

**Comment by TankNee** [comment]
参考这个issue #24 
把私有部署网址最后的`/`去掉就好了

**Comment by TankNee** [comment]
不过没有错误提示确实是个问题，我调整一下
