### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by starsareintherose** [TankNee/Neeto-Vue#63]
无法创建笔记、文件夹，也无法同步

**Comment by TankNee** [comment]
您好，能否提供一下以下几点信息：
- 用的是官方服务还是私有服务器
- 能否打开Chrome开发者工具查询错误请求
- 如果是私有服务器，能否正常访问

**Comment by starsareintherose** [comment]
私有自建
chrome ok
能正常访问
我现在已经不再使用wiznote，改用leanote。因为wiznote lite不能向PC同步，同时不能写入，该软件只是不能写入

**Comment by TankNee** [comment]
> 私有自建
> chrome ok
> 能正常访问
> 我现在已经不再使用wiznote，改用leanote。因为wiznote lite不能向PC同步，同时不能写入，该软件只是不能写入

能否提供一下创建笔记之后的网络请求？创建笔记，然后打开Neeto-Vue的Chrome开发者工具（Windows：Ctrl+Shift+I, Mac：Window -> Developer Tool），找到NetWork标签页，把XHR请求截图出来。

**Comment by TankNee** [comment]
或者您是否能提供一个测试账号？

**Comment by TankNee** [comment]
官网服务是正常的吗？

**Comment by starsareintherose** [comment]
抱歉，我因为这个问题已经卸载了，所以不能提供更多详细信息。

**Comment by TankNee** [comment]
非常抱歉没能提供良好的使用体验。
